"""
Column Generation for CSLAP using Gurobi Optimizer (Synthetic Data Adapter)

Implements the CG framework from the paper:
- Master problem: pattern selection LP (relaxed)
- Exact pricing subproblems via Gurobi: one per station, generating new patterns
- Final binary resolution step

Enhancements (Price-and-Branch matheuristic):
  1. Basis Enrichment   : enrich_warm_start() mutates the warm-start to create
                          additional diverse initial patterns before the CG loop.
  2. Two-Phase Pricing  : heuristic_pricing() runs O(N log N) before the exact
                          Gurobi subproblem; skips Gurobi when heuristic succeeds.
  3. Solution Pooling   : Gurobi pricing extracts up to 10 profitable columns per
                          call (PoolSearchMode=2, PoolSolutions=10).
"""

import numpy as np
import pandas as pd
import gurobipy as gp
from gurobipy import GRB
import os
import time
import random
import argparse
from collections import defaultdict


def read_data(prefix, data_dir):
    orders_df = pd.read_csv(
        os.path.join(data_dir, f"{prefix}_orders.csv"), sep=";"
    )
    stations_df = pd.read_csv(
        os.path.join(data_dir, f"{prefix}_stations.csv"), sep=";"
    )
    products_df = pd.read_csv(
        os.path.join(data_dir, f"{prefix}_products.csv"), sep=";"
    )
    prod_lines = orders_df.groupby("PRODUCT").size().to_dict()
    order_prods = orders_df.groupby("ORDER")["PRODUCT"].apply(list).to_dict()
    stations = stations_df.to_dict(orient="records")
    products = products_df["PRODUCT_ID"].apply(lambda x: f"PROD_{x}").tolist()
    return order_prods, stations, products, prod_lines


def generate_initial_patterns(products, stations, prod_lines):
    """
    Generate one initial pattern per station by distributing products
    in order of descending frequency, respecting capacity.
    """
    station_ids = [s["STATION_ID"] for s in stations]
    capacities = {s["STATION_ID"]: s["CAPACITY"] for s in stations}

    sorted_prods = sorted(products, key=lambda p: prod_lines.get(p, 0), reverse=True)

    patterns = {s: [] for s in station_ids}
    remaining = dict(capacities)
    idx = 0

    for p in sorted_prods:
        placed = False
        for attempt in range(len(station_ids)):
            sid = station_ids[(idx + attempt) % len(station_ids)]
            if remaining[sid] > 0:
                patterns[sid].append(p)
                remaining[sid] -= 1
                idx = (idx + attempt + 1) % len(station_ids)
                placed = True
                break
        if not placed:
            for sid in station_ids:
                patterns[sid].append(p)
                break
    return patterns


def evaluate_assignment(assignment, order_prods):
    total_visits = 0
    for o, prods in order_prods.items():
        visited = set()
        for p in prods:
            if p in assignment:
                visited.add(assignment[p])
        total_visits += len(visited)
    return total_visits


# ---------------------------------------------------------------------------
# TASK 1 — BASIS ENRICHMENT
# ---------------------------------------------------------------------------

def enrich_warm_start(warm_start_assignment, products, stations, prod_lines,
                      num_mutations=10):
    """
    Take the warm-start assignment and create `num_mutations` additional
    feasible patterns per station by randomly displacing 5‑10% of products
    and reassigning them greedily.

    Returns
    -------
    extra_patterns : dict  {station_id: [list_of_pattern_lists]}
        Each value is a list of patterns (each pattern is a list of product IDs)
        generated by mutation. Does NOT include the original warm-start pattern.
    """
    station_ids = [s["STATION_ID"] for s in stations]
    capacities   = {s["STATION_ID"]: s["CAPACITY"]      for s in stations}
    time_caps    = {s["STATION_ID"]: s["TIME_CAPACITY"]  for s in stations}
    speeds       = {s["STATION_ID"]: s["SPEED"]          for s in stations}

    # Build base dict: station -> set of products
    base = defaultdict(list)
    for p, sid in warm_start_assignment.items():
        if sid in capacities:
            base[sid].append(p)

    extra_patterns = {s: [] for s in station_ids}

    for _ in range(num_mutations):
        # Deep copy current assignment
        current = {s: list(base[s]) for s in station_ids}

        # Identify products to displace (5–10% of total, minimum 1)
        all_assigned = [(p, s) for s in station_ids for p in current[s]]
        n_displace = max(1, int(len(all_assigned) * random.uniform(0.05, 0.10)))
        displaced_pairs = random.sample(all_assigned, min(n_displace, len(all_assigned)))

        displaced_prods = []
        for p, s in displaced_pairs:
            current[s].remove(p)
            displaced_prods.append(p)

        # Shuffle displaced products and reassign greedily to a random station
        random.shuffle(displaced_prods)
        station_order = list(station_ids)
        random.shuffle(station_order)

        for p in displaced_prods:
            pl = prod_lines.get(p, 0)
            placed = False
            random.shuffle(station_order)
            for sid in station_order:
                cur_time = sum(prod_lines.get(q, 0) / speeds[sid]
                               for q in current[sid]) if speeds[sid] > 0 else 0
                time_cost = pl / speeds[sid] if speeds[sid] > 0 else 0
                if (len(current[sid]) < capacities[sid] and
                        cur_time + time_cost <= time_caps[sid]):
                    current[sid].append(p)
                    placed = True
                    break
            if not placed:
                # Fallback: place in first station that has remaining capacity
                for sid in station_order:
                    if len(current[sid]) < capacities[sid]:
                        current[sid].append(p)
                        placed = True
                        break

        # Record valid patterns (non-empty ones)
        for s in station_ids:
            if current[s]:
                extra_patterns[s].append(list(current[s]))

    return extra_patterns


# ---------------------------------------------------------------------------
# TASK 2 — DUAL-AWARE HEURISTIC PRICING
# ---------------------------------------------------------------------------

def heuristic_pricing(s, products, order_prods, capacities, time_caps, speeds,
                      prod_lines, sigma, pi_s):
    """
    O(N log N) greedy pricing heuristic using LP dual information.

    Score for product p:  score_p = sigma[p] / time_cost_p
        where time_cost_p = prod_lines[p] / speeds[s]   (0 → very large score)

    Greedily builds a pattern until CAPACITY or TIME_CAPACITY is exhausted,
    then computes the exact reduced cost:
        RC = Σ_{o : pattern covers o} z_o  −  Σ_{p in pattern} sigma[p]  −  pi_s

    Returns
    -------
    (pattern, rc) : (list[str], float)  if a pattern was built
    (None, None)                         if the station generated nothing
    """
    scored = []
    for p in products:
        pl = prod_lines.get(p, 0)
        time_cost = pl / speeds[s] if speeds[s] > 0 else 0
        if time_cost == 0:
            score = 1e9 * sigma.get(p, 0)
        else:
            score = sigma.get(p, 0) / time_cost
        scored.append((p, score, pl, time_cost))

    scored.sort(key=lambda x: -x[1])

    pattern = []
    total_time = 0.0
    for p, score, pl, tc in scored:
        if len(pattern) >= capacities[s]:
            break
        if total_time + tc <= time_caps[s]:
            pattern.append(p)
            total_time += tc

    if not pattern:
        return None, None

    # Compute exact reduced cost
    pattern_set = set(pattern)
    z_count = sum(
        1 for o, prods in order_prods.items()
        if any(pp in pattern_set for pp in prods)
    )
    rc = z_count - sum(sigma.get(p, 0) for p in pattern) - pi_s

    return pattern, rc


# ---------------------------------------------------------------------------
# MAIN COLUMN GENERATION
# ---------------------------------------------------------------------------

def column_generation_gurobi(
    order_prods, stations, products, prod_lines,
    time_limit=300, max_cg_iterations=50, warm_start_assignment=None,
    scenario_name="unknown"
):
    """
    CG framework with Gurobi (Price-and-Branch matheuristic):
    1. Basis Enrichment: enrich warm-start with mutated patterns
    2. Solve master (LP relaxed) -> get exact dual values (sigma_p, pi_s)
    3. Two-Phase Pricing: heuristic first, Gurobi exact + pool fallback
    4. Repeat until convergence or time limit
    5. Final binary resolution
    """
    start_time = time.time()

    station_ids = [s["STATION_ID"] for s in stations]
    capacities = {s["STATION_ID"]: s["CAPACITY"] for s in stations}
    time_caps  = {s["STATION_ID"]: s["TIME_CAPACITY"] for s in stations}
    speeds     = {s["STATION_ID"]: s["SPEED"] for s in stations}
    orders     = list(order_prods.keys())

    # -----------------------------------------------------------------------
    # --- Initial patterns (with optional basis enrichment) ---
    # -----------------------------------------------------------------------
    if warm_start_assignment is not None:
        print("  CG: Using provided warm start assignment for initial patterns...")
        init_patterns = {s["STATION_ID"]: [] for s in stations}
        for p, s in warm_start_assignment.items():
            if s in init_patterns:
                init_patterns[s].append(p)

        # TASK 1: Enrich with mutated patterns
        print("  CG: Enriching warm start with basis mutations...")
        extra = enrich_warm_start(
            warm_start_assignment, products, stations, prod_lines,
            num_mutations=10
        )
    else:
        print("  CG: Generating initial patterns (frequency heuristic)...")
        init_patterns = generate_initial_patterns(products, stations, prod_lines)
        extra = None

    # Register original warm-start (or heuristic) patterns
    K_s = {s: [] for s in station_ids}
    all_patterns = {}

    def _register_pattern(s, pattern):
        """Add pattern to K_s and all_patterns; return pattern_id or None if dup."""
        new_set = set(pattern)
        if not new_set:
            return None
        for k in K_s[s]:
            if set(all_patterns[k]) == new_set:
                return None   # duplicate
        pid = f"k_{s}_{len(K_s[s]) + 1}"
        K_s[s].append(pid)
        all_patterns[pid] = list(pattern)
        return pid

    for s in station_ids:
        pid = _register_pattern(s, init_patterns[s])
        if pid is None and init_patterns[s]:
            # Force at least one pattern per station
            pid = f"k_{s}_1"
            K_s[s].append(pid)
            all_patterns[pid] = list(init_patterns[s])

    # Inject enriched patterns
    if extra is not None:
        n_enriched = 0
        for s in station_ids:
            for mut_pattern in extra[s]:
                pid = _register_pattern(s, mut_pattern)
                if pid is not None:
                    n_enriched += 1
        print(f"  CG: Injected {n_enriched} enriched patterns across all stations.")

    # Precompute delta and z_osk
    delta = {}
    z_osk = {}

    def update_pattern_data(s, k, pattern):
        pattern_set = set(pattern)
        for p in products:
            delta[(p, s, k)] = 1 if p in pattern_set else 0
        for o in orders:
            prods_set = set(order_prods[o])
            z_osk[(o, s, k)] = 1 if bool(prods_set & pattern_set) else 0

    for s in station_ids:
        for k in K_s[s]:
            update_pattern_data(s, k, all_patterns[k])

    env = gp.Env(empty=True)
    env.setParam("OutputFlag", 0)
    env.start()

    log_data = {
        "scenario_name": scenario_name,
        "num_orders": len(orders),
        "num_products": len(products),
        "num_stations": len(stations),
        "station_capacity": capacities[station_ids[0]],
        "station_time_capacity": time_caps[station_ids[0]],
        "starting_master_obj": None,
        "total_iterations": 0,
        "heuristic_pricing_calls": 0,
        "exact_pricing_calls": 0,
        "lower_bound": None
    }

    for iteration in range(1, max_cg_iterations + 1):
        log_data["total_iterations"] = iteration
        elapsed = time.time() - start_time
        if elapsed > time_limit:
            print(f"  CG: Time limit reached at iteration {iteration}")
            break

        print(f"  CG Iteration {iteration}...")

        # -------------------------------------------------------------------
        # --- Master Problem (LP Relaxation) ---
        # -------------------------------------------------------------------
        rmp = gp.Model("RMP", env=env)
        rmp.setParam('OutputFlag', 0)
        
        # Memory optimization for RMP
        rmp.setParam('Threads', 2)
        rmp.setParam('Method', 2)

        y = {}
        for s in station_ids:
            for k in K_s[s]:
                y[(s, k)] = rmp.addVar(lb=0.0, ub=1.0, vtype=GRB.CONTINUOUS,
                                       name=f"y_{s}_{k}")

        rmp.setObjective(
            gp.quicksum(z_osk.get((o, s, k), 0) * y[(s, k)]
                        for o in orders for s in station_ids for k in K_s[s]),
            GRB.MINIMIZE
        )

        cov_constrs = {}
        for p in products:
            cov_constrs[p] = rmp.addConstr(
                gp.quicksum(delta.get((p, s, k), 0) * y[(s, k)]
                            for s in station_ids for k in K_s[s]) >= 1,
                name=f"cov_{p}"
            )

        pat_constrs = {}
        for s in station_ids:
            pat_constrs[s] = rmp.addConstr(
                gp.quicksum(y[(s, k)] for k in K_s[s]) <= 1,
                name=f"pat_{s}"
            )

        rmp.optimize()

        if rmp.Status != GRB.OPTIMAL:
            print(f"    RMP failed with status {rmp.Status}")
            break

        print(f"    Master objective (LP): {rmp.ObjVal:.3f}")
        
        if log_data["starting_master_obj"] is None:
            log_data["starting_master_obj"] = rmp.ObjVal
        
        log_data["lower_bound"] = rmp.ObjVal # Will be valid LB if pricing converges

        sigma = {p: cov_constrs[p].Pi for p in products}
        pi    = {s: pat_constrs[s].Pi for s in station_ids}

        # -------------------------------------------------------------------
        # --- Pricing Subproblems (Two-Phase: heuristic then exact+pool) ---
        # -------------------------------------------------------------------
        new_patterns_found = False
        remaining_time_for_pricing = max(
            5, int(time_limit - (time.time() - start_time)) // len(station_ids)
        )

        for s in station_ids:
            # ---------------------------------------------------------------
            # TASK 2 — Heuristic pricing first
            # ---------------------------------------------------------------
            log_data["heuristic_pricing_calls"] += 1
            h_pattern, h_rc = heuristic_pricing(
                s, products, order_prods,
                capacities, time_caps, speeds,
                prod_lines, sigma, pi[s]
            )

            if h_rc is not None and h_rc < -1e-4:
                pid = _register_pattern(s, h_pattern)
                if pid is not None:
                    update_pattern_data(s, pid, h_pattern)
                    new_patterns_found = True
                    print(f"    [Heuristic] Added pattern {pid} for st. {s} "
                          f"(RC={h_rc:.4f})")
                # Skip Gurobi for this station — heuristic succeeded
                continue

            # ---------------------------------------------------------------
            # TASK 3 — Exact Gurobi pricing with solution pooling
            # ---------------------------------------------------------------
            log_data["exact_pricing_calls"] += 1
            sp = gp.Model(f"Pricing_{s}", env=env)
            sp.setParam("OutputFlag", 0)
            sp.setParam('TimeLimit', remaining_time_for_pricing)
            # Solution pool settings
            sp.setParam('PoolSearchMode', 2)
            sp.setParam('PoolSolutions', 10)
            
            # Memory optimization for Pricing
            sp.setParam("NodefileStart", 4.0)
            sp.setParam("Threads", 2)
            sp.setParam("Presolve", 1)

            a    = sp.addVars(products, vtype=GRB.BINARY, name="a")
            z_sp = sp.addVars(orders, lb=0.0, ub=1.0,
                              vtype=GRB.CONTINUOUS, name="z")

            sp.addConstr(gp.quicksum(a[p] for p in products) <= capacities[s],
                         name="cap")
            sp.addConstr(
                gp.quicksum((prod_lines.get(p, 0) / speeds[s]) * a[p]
                            for p in products) <= time_caps[s],
                name="workload"
            )

            for o in orders:
                for p in order_prods[o]:
                    if p in products:
                        sp.addConstr(z_sp[o] >= a[p], name=f"link_{o}_{p}")

            sp.setObjective(
                gp.quicksum(z_sp[o] for o in orders)
                - gp.quicksum(sigma[p] * a[p] for p in products)
                - pi[s],
                GRB.MINIMIZE
            )

            sp.optimize()

            if sp.Status in [GRB.OPTIMAL, GRB.TIME_LIMIT] and sp.SolCount > 0:
                # TASK 3: Extract all profitable solutions from the pool
                for i in range(sp.SolCount):
                    sp.setParam('SolutionNumber', i)
                    rc = sp.PoolObjVal
                    if rc < -1e-4:
                        new_pattern = [p for p in products if a[p].Xn > 0.5]
                        pid = _register_pattern(s, new_pattern)
                        if pid is not None and new_pattern:
                            update_pattern_data(s, pid, new_pattern)
                            new_patterns_found = True
                            print(f"    [Pool sol {i}] Added {pid} for st. {s} "
                                  f"(RC={rc:.4f})")

        if not new_patterns_found:
            print(f"  CG: No negative reduced cost patterns found. Converged. LB={log_data['lower_bound']:.3f}")
            break
        else:
            log_data["lower_bound"] = "Not rigorosly proven bound due to heuristic pricing / time limit"

    # -----------------------------------------------------------------------
    # --- Final Binary Resolution ---
    # -----------------------------------------------------------------------
    print("  CG: Solving final Integer Master Problem...")
    imp = gp.Model("IMP", env=env)
    imp.setParam('OutputFlag', 0)
    imp.setParam('TimeLimit', max(10, time_limit - (time.time() - start_time)))
    
    # Memory optimization for IMP
    imp.setParam("NodefileStart", 4.0)
    imp.setParam("Threads", 2)

    y = {}
    for s in station_ids:
        for k in K_s[s]:
            y[(s, k)] = imp.addVar(vtype=GRB.BINARY, name=f"y_{s}_{k}")

    imp.setObjective(
        gp.quicksum(z_osk.get((o, s, k), 0) * y[(s, k)]
                    for o in orders for s in station_ids for k in K_s[s]),
        GRB.MINIMIZE
    )

    for p in products:
        imp.addConstr(
            gp.quicksum(delta.get((p, s, k), 0) * y[(s, k)]
                        for s in station_ids for k in K_s[s]) >= 1,
            name=f"cov_{p}"
        )

    for s in station_ids:
        imp.addConstr(gp.quicksum(y[(s, k)] for k in K_s[s]) <= 1,
                      name=f"pat_{s}")

    imp.optimize()
    elapsed = time.time() - start_time

    best_assignment = {}
    total_visits = float('inf')

    if imp.Status in [GRB.OPTIMAL, GRB.TIME_LIMIT] and imp.SolCount > 0:
        for s in station_ids:
            for k in K_s[s]:
                if y[(s, k)].X > 0.5:
                    for p in all_patterns[k]:
                        best_assignment[p] = s

        total_visits = evaluate_assignment(best_assignment, order_prods)

        station_counts   = defaultdict(int)
        station_workload = defaultdict(float)
        for p, sid in best_assignment.items():
            station_counts[sid]   += 1
            station_workload[sid] += prod_lines.get(p, 0)

        cap_broken = sum(1 for sid in station_ids
                         if station_counts[sid] > capacities[sid])

        actual_workloads = []
        for sid in station_ids:
            time_spent = (station_workload[sid] / speeds[sid]
                          if speeds[sid] > 0 else 0)
            actual_workloads.append(time_spent)

        wl_broken = sum(1 for i, sid in enumerate(station_ids)
                        if actual_workloads[i] > time_caps[sid])

        max_workload      = float(np.max(actual_workloads)) if actual_workloads else 0.0
        workload_std_dev = float(np.std(actual_workloads)) if actual_workloads else 0.0

        print(f"  CG Done: Visits={total_visits}, Time={elapsed:.2f}s, "
              f"WL_Std={workload_std_dev:.4f}, Max_WL={max_workload:.4f}, "
              f"Cap_Broken={cap_broken}, WL_Broken={wl_broken}")

        # Save the log
        log_dir = "logs"
        os.makedirs(log_dir, exist_ok=True)
        timestamp = time.strftime("%Y%md_%H%M%S")
        log_file = os.path.join(log_dir, f"cg_gurobi_scenario_log_{scenario_name}_{timestamp}.txt")
        with open(log_file, "w") as f:
            for k, v in log_data.items():
                f.write(f"{k}: {v}\n")

        return best_assignment, total_visits, elapsed, max_workload, workload_std_dev, cap_broken, wl_broken

    print(f"  CG: No feasible solution found in {time_limit}s.")
    return None, None, elapsed, None, None, None, None


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="CG CSLAP (Gurobi, synthetic)")
    parser.add_argument("--prefix", type=str, required=True)
    parser.add_argument("--dir",    type=str, default="synthetic_datasets")
    parser.add_argument("--time",   type=int, default=300)
    args = parser.parse_args()

    print(f"Running CG on {args.prefix}...")
    order_prods, stations, products, prod_lines = read_data(args.prefix, args.dir)
    column_generation_gurobi(
        order_prods, stations, products, prod_lines, time_limit=args.time,
        scenario_name=args.prefix
    )
